---
- name: Configure monitoring
  hosts: all
  sudo: True
  gather_facts: True
  vars:
    COMMON_ENABLE_DATADOG: True
    SANDBOX_ENABLE_ECOMMERCE: False
    COMMON_ENABLE_SPLUNKFORWARDER: False
    COMMON_ENABLE_NEWRELIC: True
  roles:
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
